version: '3.8'

services:
  web:
    build:
      context: ./app      # Points to the app folder
      dockerfile: Dockerfile
    container_name: flask-web
    ports:
      - "5000:5000"
    restart: always
