name: Deploy Flask App to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-flask:latest ./app

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-flask:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-flask:latest
          sudo docker stop $(sudo docker ps -q) || true
          sudo docker run -d -p 80:5000 ${{ secrets.DOCKERHUB_USERNAME }}/devops-flask:latest
          sudo docker ps
