name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # Runs whenever code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Docker image
        run: |
          cd app
          docker build -t flask-app:latest .

      - name: Save Docker image to file
        run: docker save flask-app:latest -o flask-app.tar

      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_DNS }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "flask-app.tar"
          target: "/home/ec2-user/"

      - name: Deploy and run container on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PUBLIC_DNS }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load -i flask-app.tar
            docker stop flask-app || true
            docker rm flask-app || true
            docker run -d -p 80:5000 --name flask-app flask-app:latest
